export const CHECK_USER_AUTH_REJECTED = "CHECK_USER_AUTH_REJECTED";
export const CHECK_USER_AUTH_FULFILLED = "CHECK_USER_AUTH_FULFILLED";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_FULFILLED = "FETCH_QUESTIONS_FULFILLED";
export const FETCH_QUESTIONS_REJECTED = "FETCH_QUESTIONS_REJECTED";
