export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_FULFILLED = 'USER_AUTH_FULFILLED';
export const USER_AUTH_REJECTED = 'USER_AUTH_REJECTED';

export const LOGIN = 'LOGIN';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';

export const LOGOUT_TEST = 'LOGOUT_TEST';
