export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
