import { zipObject } from 'lodash';

const actions = [
  'FETCH_ALL_QUESTION_BANK_REQUEST',
  'FETCH_ALL_QUESTION_BANK_SUCCESS',
  'FETCH_ALL_QUESTION_BANK_FAILURE',

  'FETCH_ALL_QUESTIONS_BY_QUESTION_BANK_REQUEST',
  'FETCH_ALL_QUESTIONS_BY_QUESTION_BANK_SUCCESS',
  'FETCH_ALL_QUESTIONS_BY_QUESTION_BANK_FAILURE',

  'CREATE_QUESTION_BY_QUESTION_BANK_REQUEST',
  'CREATE_QUESTION_BY_QUESTION_BANK_SUCCESS',
  'CREATE_QUESTION_BY_QUESTION_BANK_FAILURE',
];

export default zipObject(actions, actions);
